### ISSUE TITLE
@import not supported by reddit

### ISSUE THREAD

**Issue by Fuzzylog1cza** [adderlan/reddit.sea#1]
We have to remove the @import statement in the CSS. That functionality is not supported by reddit. Ideally we will just replace header text with a transparent PNG over the banner and pick a supported font for the thread titles.

**Comment by adderlan** [comment]
What's worse is that certain parts of the layout (tabs) were dependent on font sizes, which I didn't even notice until I disabled the Google font.

DoH!

So special fonts are out, and I restyled the 'banner tab' to look a little more 'piratey' to compensate. At this point I actually think we can aesthetically get away with just using the default fonts.
